image: 8u191-jdk-alpine3.8

before_script:
  - pwd
  - ls -l

stages:
  - build
  - quality
  - deploy

build:
  stage: build
  script: ./gradlew 
  artifacts:
    paths:
      - node_modules
    expire_in: 1 day

lint:
  stage: quality
  script: ./gradlew clean lint

unit_test:
  stage: quality
  script: ./gradlew clean test

coverage_test:
  stage: quality
  script: ./gradlew clean coverage_test

load_test:
  stage: quality
  script: ./gradlew clean load_test

deploy_to_production:
  stage: deploy
  script:
    - echo "There is no deploy yet"
    - exit 1
